version: '3.8'

services:
  # Service cho ứng dụng Spring Boot
  be-spring-boot:
    image: be-spring-boot:0.0.1
    ports:
      - "8085:8085"
    depends_on:
      - httuyensinhdb

  # Service cho cơ sở dữ liệu MySQL
  httuyensinhdb:
    container_name: httuyensinhdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin@123"
      MYSQL_DATABASE: "httuyensinhdb"
